import redbullLogo from "../assets/team_logo/red-bull-racing-logo.png";
import ferrariLogo from "../assets/team_logo/ferrari-logo.png";
import mclarenLogo from "../assets/team_logo/mclaren-logo.png";
import mercedesLogo from "../assets/team_logo/mercedes-logo.png";
import astonmartinLogo from "../assets/team_logo/aston-martin-logo.png";
import rbLogo from "../assets/team_logo/rb-logo.png";
import haasLogo from "../assets/team_logo/haas-logo.png";
import alpineLogo from "../assets/team_logo/alpine-logo.png";
import williamsLogo from "../assets/team_logo/williams-logo.png";
import sauberLogo from "../assets/team_logo/kick-sauber-logo.png";

const profile = [
  {
    position: "1",
    points: "255",
    teamName: "RedBull",
    driverName: "Max VERSTAPPEN",
    driverProfile: "./src/assets/player/maxver01.png",
    teamColor: "rgb(54 113 198 / 1)",
    nameCode: "VER",
    teamLogo: redbullLogo,
    nation: "/src/assets/nation/Netherlands.jpg",
    number: "/src/assets/numberr/MAXVER01.png",
  },
  {
    position: "6",
    points: "118",
    teamName: "RedBull",
    driverName: "Sergio PEREZ",
    driverProfile: "./src/assets/player/serper01.png",
    teamColor: "rgb(54 113 198 / 1)",
    nameCode: "PER",
    teamLogo: redbullLogo,
    nation: "/src/assets/nation/Mexico.jpg",
    number: "/src/assets/numberr/SERPER01.png",
  },
  {
    position: "3",
    points: "150",
    teamName: "Ferrari",
    driverName: "Charles LECLERC",
    driverProfile: "./src/assets/player/chalec01.png",
    teamColor: "rgb(232 0 32 /1)",
    nameCode: "LEC",
    teamLogo: ferrariLogo,
    nation: "/src/assets/nation/Monaco.jpg",
    number: "/src/assets/numberr/CHALEC01.png",
  },
  {
    position: "4",
    points: "146",
    teamName: "Ferrari",
    driverName: "Carlos SAINZ",
    driverProfile: "./src/assets/player/carsai01.png",
    teamColor: "rgb(232 0 32 /1)",
    nameCode: "SAI",
    teamLogo: ferrariLogo,
    nation: "/src/assets/nation/Spain.jpg",
    number: "/src/assets/numberr/CARSAI01.png",
  },
  {
    position: "2",
    points: "171",
    teamName: "Mclaren",
    driverName: "Lando NORRIS",
    driverProfile: "./src/assets/player/lannor01.png",
    teamColor: "rgb(255 128 0 /1)",
    nameCode: "NOR",
    teamLogo: mclarenLogo,
    nation: "/src/assets/nation/United_Kingdom.jpg",
    number: "/src/assets/numberr/LANNOR01.png",
  },
  {
    position: "5",
    points: "124",
    teamName: "Mclaren",
    driverName: "Oscar PIASTRI",
    driverProfile: "./src/assets/player/oscpia01.png",
    teamColor: "rgb(255 128 0 /1)",
    nameCode: "PIA",
    teamLogo: mclarenLogo,
    nation: "/src/assets/nation/Australia.jpg",
    number: "/src/assets/numberr/OSCPIA01.png",
  },
  {
    position: "8",
    points: "110",
    teamName: "Mercedes",
    driverName: "Lewis HAMILTON",
    driverProfile: "./src/assets/player/lewham01.png",
    teamColor: "rgb(39 244 210/1)",
    nameCode: "HAM",
    teamLogo: mercedesLogo,
    nation: "/src/assets/nation/United_Kingdom.jpg",
    number: "/src/assets/numberr/LEWHAM01.png",
  },
  {
    position: "7",
    points: "111",
    teamName: "Mercedes",
    driverName: "George RUSSELL",
    driverProfile: "./src/assets/player/georus01.png",
    teamColor: "rgb(39 244 210/1)",
    nameCode: "RUS",
    teamLogo: mercedesLogo,
    nation: "/src/assets/nation/United_Kingdom.jpg",
    number: "/src/assets/numberr/GEORUS01.png",
  },
  {
    position: "9",
    points: "45",
    teamName: "Aston Martin",
    driverName: "Fernando ALONSO",
    driverProfile: "./src/assets/player/feralo01.png",
    teamColor: "rgb(34 153 113/1)",
    nameCode: "ALO",
    teamLogo: astonmartinLogo,
    nation: "/src/assets/nation/Spain.jpg",
    number: "/src/assets/numberr/FERALO01.png",
  },
  {
    position: "10",
    points: "23",
    teamName: "Aston Martin",
    driverName: "Lance STROLL",
    driverProfile: "./src/assets/player/lanstr01.png",
    teamColor: "rgb(34 153 113/1)",
    nameCode: "STR",
    teamLogo: astonmartinLogo,
    nation: "/src/assets/nation/Canada.jpg",
    number: "/src/assets/numberr/LANSTR01.png",
  },
  {
    position: "12",
    points: "20",
    teamName: "RB",
    driverName: "Yuki TSUNODA",
    driverProfile: "./src/assets/player/yuktsu01.png",
    teamColor: "rgb(102 146 255/1)",
    nameCode: "TSU",
    teamLogo: rbLogo,
    nation: "/src/assets/nation/Japan.jpg",
    number: "/src/assets/numberr/YUKTSU01.png",
  },
  {
    position: "13",
    points: "11",
    teamName: "RB",
    driverName: "Daniel RICCIARDO",
    driverProfile: "./src/assets/player/danric01.png",
    teamColor: "rgb(102 146 255/1)",
    nameCode: "RIC",
    teamLogo: rbLogo,
    nation: "/src/assets/nation/Australia.jpg",
    number: "/src/assets/numberr/DANRIC01.png",
  },
  {
    position: "11",
    points: "22",
    teamName: "Haas",
    driverName: "Nico HULKENBERG",
    driverProfile: "./src/assets/player/nichul01.png",
    teamColor: "rgb(182 186 189 /1)",
    nameCode: "HUL",
    teamLogo: haasLogo,
    nation: "/src/assets/nation/Germany.jpg",
    number: "/src/assets/numberr/NICHUL01.png",
  },
  {
    position: "16",
    points: "5",
    teamName: "Haas",
    driverName: "Kevin MAGNUSSEN",
    driverProfile: "./src/assets/player/kevmag01.png",
    teamColor: "rgb(182 186 189 /1)",
    nameCode: "MAG",
    teamLogo: haasLogo,
    nation: "/src/assets/nation/Denmark.jpg",
    number: "/src/assets/numberr/KEVMAG01.png",
  },
  {
    position: "15",
    points: "6",
    teamName: "Alpine",
    driverName: "Pierre GASLY",
    driverProfile: "./src/assets/player/piegas01.png",
    teamColor: "rgb(0 147 204 / 1)",
    nameCode: "GAS",
    teamLogo: alpineLogo,
    nation: "/src/assets/nation/France.jpg",
    number: "/src/assets/numberr/PIEGAS01.png",
  },
  {
    position: "18",
    points: "3",
    teamName: "Alpine",
    driverName: "Esteban OCON",
    driverProfile: "./src/assets/player/estoco01.png",
    teamColor: "rgb(0 147 204 / 1)",
    nameCode: "OCO",
    teamLogo: alpineLogo,
    nation: "/src/assets/nation/France.jpg",
    number: "/src/assets/numberr/ESTOCO01.png",
  },
  {
    position: "17",
    points: "4",
    teamName: "Williams",
    driverName: "Alexander ALBON",
    driverProfile: "./src/assets/player/alealb01.png",
    teamColor: "rgb(100 196 255  / 1)",
    nameCode: "ALB",
    teamLogo: williamsLogo,
    nation: "/src/assets/nation/Thailand.jpg",
    number: "/src/assets/numberr/ALEALB01.png",
  },
  {
    position: "20",
    points: "0",
    teamName: "Williams",
    driverName: "Logan SARGEANT",
    driverProfile: "./src/assets/player/logsar01.png",
    teamColor: "rgb(100 196 255  / 1)",
    nameCode: "SAR",
    teamLogo: williamsLogo,
    nation: "/src/assets/nation/United_States.jpg",
    number: "/src/assets/numberr/LOGSAR01.png",
  },
  {
    position: "21",
    points: "0",
    teamName: "Kick Sauber",
    driverName: "Valtteri BOTTAS",
    driverProfile: "./src/assets/player/valbot01.png",
    teamColor: "rgb(82 226 82 /1)",
    nameCode: "BOT",
    teamLogo: sauberLogo,
    nation: "/src/assets/nation/Finland.jpg",
    number: "/src/assets/numberr/VALBOT01.png",
  },
  {
    position: "19",
    points: "0",
    teamName: "Kick Sauber",
    driverName: "ZHOU Guanyu",
    driverProfile: "./src/assets/player/guazho01.png",
    teamColor: "rgb(82 226 82 /1)",
    nameCode: "ZHO",
    teamLogo: sauberLogo,
    nation: "/src/assets/nation/China.jpg",
    number: "/src/assets/numberr/GUAZHO01.png",
  },
  {
    position: "14",
    points: "6",
    teamName: "Ferrari",
    driverName: "Oliver Bearman",
    driverProfile: "",
    teamColor: "rgb(232 0 32 /1)",
    nameCode: "BEA",
    teamLogo: ferrariLogo,
    nation: "/src/assets/nation/United_Kingdom.jpg",
    number: "/src/assets/numberr/OLIBEA01.png",
  },
];

export default profile;
