const profile = [
  {
    teamName: "RedBull",
    driverName: "Max VERSTAPPEN",
    driverProfile: "./src/assets/player/maxver01.png",
    teamColor: "rgb(54 113 198 / 1)",
    nameCode: "VER",
  },
  {
    teamName: "RedBull",
    driverName: "Sergio PEREZ",
    driverProfile: "./src/assets/player/serper01.png",
    teamColor: "rgb(54 113 198 / 1)",
    nameCode: "PER",
  },
  {
    teamName: "Ferrari",
    driverName: "Charles LECLERC",
    driverProfile: "./src/assets/player/chalec01.png",
    teamColor: "rgb(232 0 32 /1)",
    nameCode: "LEC",
  },
  {
    teamName: "Ferrari",
    driverName: "Carlos SAINZ",
    driverProfile: "./src/assets/player/carsai01.png",
    teamColor: "rgb(232 0 32 /1)",
    nameCode: "SAI",
  },
  {
    teamName: "Mclaren",
    driverName: "Lando NORRIS",
    driverProfile: "./src/assets/player/lannor01.png",
    teamColor: "rgb(255 128 0 /1)",
    nameCode: "NOR",
  },
  {
    teamName: "Mclaren",
    driverName: "Oscar PIASTRI",
    driverProfile: "./src/assets/player/oscpia01.png",
    teamColor: "rgb(255 128 0 /1)",
    nameCode: "PIA",
  },
  {
    teamName: "Mercedes",
    driverName: "Lewis HAMILTON",
    driverProfile: "./src/assets/player/lewham01.png",
    teamColor: "rgb(39 244 210/1)",
    nameCode: "HAM",
  },
  {
    teamName: "Mercedes",
    driverName: "George RUSSELL",
    driverProfile: "./src/assets/player/georus01.png",
    teamColor: "rgb(39 244 210/1)",
    nameCode: "RUS",
  },
  {
    teamName: "Aston Martin",
    driverName: "Fernando ALONSO",
    driverProfile: "./src/assets/player/feralo01.png",
    teamColor: "rgb(34 153 113/1)",
    nameCode: "ALO",
  },
  {
    teamName: "Aston Martin",
    driverName: "Lance STROLL",
    driverProfile: "./src/assets/player/lanstr01.png",
    teamColor: "rgb(34 153 113/1)",
    nameCode: "STR",
  },
  {
    teamName: "RB",
    driverName: "Yuki TSUNODA",
    driverProfile: "./src/assets/player/yuktsu01.png",
    teamColor: "rgb(102 146 255/1)",
    nameCode: "TSU",
  },
  {
    teamName: "RB",
    driverName: "Daniel RICCIARDO",
    driverProfile: "./src/assets/player/danric01.png",
    teamColor: "rgb(102 146 255/1)",
    nameCode: "RIC",
  },
  {
    teamName: "Haas",
    driverName: "Nico HULKENBERG",
    driverProfile: "./src/assets/player/nichul01.png",
    teamColor: "rgb(182 186 189 /1)",
    nameCode: "HUL",
  },
  {
    teamName: "Haas",
    driverName: "Kevin MAGNUSSEN",
    driverProfile: "./src/assets/player/kevmag01.png",
    teamColor: "rgb(182 186 189 /1)",
    nameCode: "MAG",
  },
  {
    teamName: "Alpine",
    driverName: "Pierre GASLY",
    driverProfile: "./src/assets/player/piegas01.png",
    teamColor: "rgb(0 147 204 / 1)",
    nameCode: "GAS",
  },
  {
    teamName: "Alpine",
    driverName: "Esteban OCON",
    driverProfile: "./src/assets/player/estoco01.png",
    teamColor: "rgb(0 147 204 / 1)",
    nameCode: "OCO",
  },
  {
    teamName: "Williams",
    driverName: "Alexander ALBON",
    driverProfile: "./src/assets/player/alealb01.png",
    teamColor: "rgb(100 196 255  / 1)",
    nameCode: "ALB",
  },
  {
    teamName: "Williams",
    driverName: "Logan SARGEANT",
    driverProfile: "./src/assets/player/logsar01.png",
    teamColor: "rgb(100 196 255  / 1)",
    nameCode: "SAR",
  },
  {
    teamName: "Kick Sauber",
    driverName: "Valtteri BOTTAS",
    driverProfile: "./src/assets/player/valbot01.png",
    teamColor: "rgb(82 226 82 /1)",
    nameCode: "BOT",
  },
  {
    teamName: "Kick Sauber",
    driverName: "ZHOU Guanyu",
    driverProfile: "./src/assets/player/guazho01.png",
    teamColor: "rgb(82 226 82 /1)",
    nameCode: "ZHO",
  },
  {
    teamName: "Ferrari",
    driverName: "Oliver Bearman",
    driverProfile: "",
    teamColor: "rgb(232 0 32 /1)",
    nameCode: "BEA",
  },
];

export default profile;
