export const dummyDrivers = [
  {
    position: " 1",
    name: "Max Verstappen",
    firstName: "Max",
    lastName: "Verstappen",
    namecode: "VER",
    points: "0",
    country: "Netherlands",
    team: "Red Bull Racing",
    dateOfBirth: "1997-09-30",
  },
  {
    position: " 2",
    name: "Sergio Perez",
    firstName: "Sergio",
    lastName: "Perez",
    namecode: "PER",
    points: "0",
    country: "Mexico",
    team: "Red Bull Racing",
    dateOfBirth: "1990-01-26",
  },
  {
    position: " 3",
    name: "Lewis Hamilton",
    firstName: "Lewis",
    lastName: "Hamilton",
    namecode: "HAM",
    points: "0",
    country: "United Kingdom",
    team: "Mercedes",
    dateOfBirth: "1985-01-07",
  },
  {
    position: " 4",
    name: "Charles Leclerc",
    firstName: "Charles",
    lastName: "Leclerc",
    namecode: "LEC",
    points: "0",
    country: "Monaco",
    team: "Ferrari",
    dateOfBirth: "1997-10-16",
  },
  {
    position: " 5",
    name: "Carlos Sainz",
    firstName: "Carlos",
    lastName: "Sainz",
    namecode: "SAI",
    points: "0",
    country: "Spain",
    team: "Ferrari",
    dateOfBirth: "1994-09-01",
  },
  {
    position: " 6",
    name: "Lando Norris",
    firstName: "Lando",
    lastName: "Norris",
    namecode: "NOR",
    points: "0",
    country: "United Kingdom",
    team: "McLaren",
    dateOfBirth: "1999-11-13",
  },
  {
    position: " 7",
    name: "George Russell",
    firstName: "George",
    lastName: "Russell",
    namecode: "RUS",
    points: "0",
    country: "United Kingdom",
    team: "Mercedes",
    dateOfBirth: "1998-02-15",
  },
  {
    position: " 8",
    name: "Fernando Alonso",
    firstName: "Fernando",
    lastName: "Alonso",
    namecode: "ALO",
    points: "0",
    country: "Spain",
    team: "Aston Martin",
    dateOfBirth: "1981-07-29",
  },
  {
    position: " 9",
    name: "Oscar Piastri",
    firstName: "Oscar",
    lastName: "Piastri",
    namecode: "PIA",
    points: "0",
    country: "Australia",
    team: "McLaren",
    dateOfBirth: "2001-04-06",
  },
  {
    position: "10",
    name: "Pierre Gasly",
    firstName: "Pierre",
    lastName: "Gasly",
    namecode: "GAS",
    points: "0",
    country: "France",
    team: "Alpine",
    dateOfBirth: "1996-02-07",
  },
  {
    position: "11",
    name: "Lance Stroll",
    firstName: "Lance",
    lastName: "Stroll",
    namecode: "STR",
    points: "0",
    country: "Canada",
    team: "Aston Martin",
    dateOfBirth: "1998-10-29",
  },
  {
    position: "12",
    name: "Esteban Ocon",
    firstName: "Esteban",
    lastName: "Ocon",
    namecode: "OCO",
    points: "0",
    country: "France",
    team: "Alpine",
    dateOfBirth: "1996-09-17",
  },
  {
    position: "13",
    name: "Alexander Albon",
    firstName: "Alexander",
    lastName: "Albon",
    namecode: "ALB",
    points: "0",
    country: "Thailand",
    team: "Williams",
    dateOfBirth: "1996-03-23",
  },
  {
    position: "14",
    name: "Yuki Tsunoda",
    firstName: "Yuki",
    lastName: "Tsunoda",
    namecode: "TSU",
    points: "0",
    country: "Japan",
    team: "RB",
    dateOfBirth: "2000-05-11",
  },
  {
    position: "15",
    name: "Valtteri Bottas",
    firstName: "Valtteri",
    lastName: "Bottas",
    namecode: "BOT",
    points: "0",
    country: "Finland",
    team: "Sauber",
    dateOfBirth: "1989-08-28",
  },
  {
    position: "16",
    name: "Nico Hulkenberg",
    firstName: "Nico",
    lastName: "Hulkenberg",
    namecode: "HUL",
    points: "0",
    country: "Germany",
    team: "Haas F1 Team",
    dateOfBirth: "1987-08-19",
  },
  {
    position: "17",
    name: "Daniel Ricciardo",
    firstName: "Daniel",
    lastName: "Ricciardo",
    namecode: "RIC",
    points: "0",
    country: "Australia",
    team: "RB",
    dateOfBirth: "1989-07-01",
  },
  {
    position: "18",
    name: "Zhou Guanyu",
    firstName: "Guanyu",
    lastName: "Zhou",
    namecode: "ZHO",
    points: "0",
    country: "China",
    team: "Sauber",
    dateOfBirth: "1999-05-30",
  },
  {
    position: "19",
    name: "Kevin Magnussen",
    firstName: "Kevin",
    lastName: "Magnussen",
    namecode: "MAG",
    points: "0",
    country: "Denmark",
    team: "Haas F1 Team",
    dateOfBirth: "1992-10-05",
  },
  {
    position: "20",
    name: "Logan Sargeant",
    firstName: "Logan",
    lastName: "Sargeant",
    namecode: "SAR",
    points: "0",
    country: "United States",
    team: "Williams",
    dateOfBirth: "2000-12-31",
  },
  {
    position: "14",
    name: "Oliver Bearman",
    firstName: "Oliver",
    lastName: "Bearman",
    namecode: "BEA",
    points: "6",
    country: "United Kingdom",
    team: "Ferrari",
    dateOfBirth: "2005-08-05",
  },
];
